# Docker Compose file for ELK stack

# Build with:
# docker-compose build elk

# Run with:
# docker-compose up

rsyslog_centralized:
  image: bossjones/rsyslog:0.3.0
  # entrypoint:
  #   - /bin/sh
  # command: ['-c', 'mkdir -p /var/spool/rsyslog; mkdir -p /log/client_logs; install -o syslog /dev/null -m 640 /var/log/rsyslog-debug', "/home/appliance/starter.sh rsyslog"]
  environment:
    - _IMTCP_PORT=6170
    - _IMUDP_PORT=6160
    - _IMRELP_PORT=1601
    - RSYSLOG_CONF=/rsyslog-centralized/etc/rsyslog.conf
    - _RSYSLOG_SPOOL_PATH=/spool
    - TZ=UTC
    # - RSYSLOG_DEBUG_FLAG=-d
  volumes:
    - ./rsyslog-conf/config:/config
    - ./rsyslog-conf/log:/log
    - ./rsyslog-conf/rsyslog-centralized:/rsyslog-centralized
    - ./rsyslog-conf/spool:/spool
    - ./rsyslog-conf/work:/work

  ports:
    - "6160:6160/udp"
    - "6170:6170/tcp"
    - "1601:1601/tcp"
  links:
    - elk

fluent_bit_centralized:
  image: fluent/fluent-bit:1.8-debug
  environment:
    - TAIL_BUF_LIMIT=5MB
  volumes:
    - ./fluent-bit-centralized-conf/fluent-bit/etc:/fluent-bit/etc
    - ./fluent-bit-centralized-conf/var/fluent-bit:/var/fluent-bit
    - ./fluent-bit-centralized-conf/logging-volume:/logging-volume


  ports:
    - "2020:2020/tcp"
    - "5140:5140/udp"
  links:
    - elk
    - rsyslog_centralized


elk:
  build: .
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
  environment:
    - ES_HEAP_SIZE=2g
    - ES_JAVA_OPTS=-Xms2g -Xmx2g
    - LS_HEAP_SIZE=1g
